name: 'Restore pip cache'
description: 'Restore pip cache for the project'
runs:
  using: "composite"
  steps:
    - name: Restore Pip Cache
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ hashFiles('setup.py') }}-${{ hashFiles('requirements.txt') }}
