name: Cut new version

on:
  workflow_dispatch:

jobs:

  cut-new-version:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: pip install --upgrade bumpver
      - run: pip install ./releaseherald
      
      - name: git setup
        run: |
          git config user.name "Github Version Updater" 
          git config user.email "<>"
      - run: bumpver update
      - run: bumpver show --env > new-version.txt
      - run: releaseherald generate --latest --no-update -t news.rst
      - uses: actions/upload-artifact@v4
        with:
          name: new-version
          path: |
            new-version.txt
            news.rst

  build:
    runs-on: ubuntu-latest
    needs: cut-new-version

    steps:
      - uses: actions/checkout@v4
      - run: git pull origin
      - uses: actions/download-artifact@v3
        with:
          name: new-version
      - name: Get Version
        id: get_version
        run: |
          eval $(cat new-version.txt)
          echo "new_version=${CURRENT_VERSION}" >> $GITHUB_OUTPUT
      - uses: ./.github/actions/build-package
      - uses: ./.github/actions/create-release
        with:
          tag_name: ${{ steps.get_version.outputs.new_version }}
          package: dist/testplan-${{ steps.get_version.outputs.new_version }}-py3-none-any.whl
          news: news.rst
