name: Cut new version

on:
  workflow_dispatch:

jobs:

  cut-new-version:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
        with:
          fetch-depth: 0
      - uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
        with:
          python-version: '3.11'

      - run: pip install --upgrade pip
      - run: pip install bumpver
      
      - name: git setup
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config push.autoSetupRemote true          

      - name: bump version and open pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git checkout -b bump_version_tmp
          bumpver update
          eval `bumpver show --environ`
          NEW_BRANCH="bump_version/${CURRENT_VERSION}"
          git branch -m bump_version_tmp ${NEW_BRANCH}
          git push origin
          gh pr create --title "Bump version: ${CURRENT_VERSION}" --body "Bump version: ${CURRENT_VERSION}, please merge it to continue pypi publishing." --base main --head ${NEW_BRANCH} 
